function downloadReport(data) {


const reportWindow = window.open("", "_blank");



reportWindow.document.write(`

<!DOCTYPE html>

<html>

<head>

<title>
FileDetective Report
</title>


<style>

body{

font-family:Manrope,Arial,sans-serif;

background:#0f172a;

color:white;

padding:40px;

line-height:1.7;

}


.container{

max-width:800px;

margin:auto;

background:#111827;

padding:35px;

border-radius:20px;

}


h1{

font-size:32px;

margin-bottom:5px;

}


.subtitle{

color:#94a3b8;

margin-bottom:30px;

}


.card{

background:#1e293b;

padding:20px;

border-radius:15px;

margin-bottom:20px;

}


.card h2{

font-size:20px;

margin-bottom:15px;

}


pre{

white-space:pre-wrap;

font-family:inherit;

}


.footer{

margin-top:30px;

color:#94a3b8;

font-size:14px;

}


</style>


</head>



<body>


<div class="container">


<h1>
🔍 FileDetective
</h1>


<div class="subtitle">
Private File Analysis Report
</div>


<button onclick="window.print()" 
style="
margin-top:20px;
padding:12px 24px;
border:none;
border-radius:12px;
background:#2563EB;
color:white;
font-size:16px;
cursor:pointer;
">
⬇ Save / Download Report
</button>



<div class="card">

<h2>
General Information
</h2>

<pre>
${data.general}
</pre>

</div>

<div class="card">

<h2>
Security Analysis
</h2>

<pre>
${data.security}
</pre>

</div>




<div class="card">

<h2>
Metadata
</h2>

<pre>
${data.metadata}
</pre>

</div>




<div class="card">

<h2>
File Hashes
</h2>

<pre>
${data.hash}
</pre>

</div>




<div class="card">

<h2>
Privacy Notice
</h2>

<p>

This report was generated locally by FileDetective.
Your file was never uploaded to any server.

</p>


</div>




<div class="footer">

Generated by FileDetective © 2026

</div>



</div>


</body>


</html>

`);



reportWindow.document.close();



}
